apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::901436154577:role/eksctl-myFSNDCluster-nodegroup-ng--NodeInstanceRole-xMdPijbOM9C1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
     rolearn: arn:aws:iam::901436154577:role/UdacityFlaskDeployCBKubectlRole
     username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-19T08:37:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1487"
  uid: 1b8e443a-af98-40dd-8abb-235aa8446f9b
